# Set build language to Python
language: python

# Set python version to 3.7
python: 3.7

install:
  - python setup.py install
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install numpy==1.17.2
  - pip install torch
  - pip install torchvision
script:
  - chmod +x setup.py
  - pytest --cov=./

# Report results to DeepSource
after_success:
  # Generate coverage report in xml format
  - pytest --cov-report xml

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # Report coverage artifact to 'test-coverage' analyzer
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
